### ISSUE TITLE
包的路径问题

### ISSUE THREAD

**Issue by huangxiang360729** [scaomath/galerkin-transformer#7]
* 用命令 “pip install galerkin-transformer”, 可以安装好这个包:
``` shell
Installing collected packages: galerkin-transformer
Successfully installed galerkin-transformer-0.1.1
``` 

* 但是当我调用 “from galerkin_transformer.model import *” 语句时，会出现如下错误：
``` shell
Traceback (most recent call last):
  File "xxx/lib/python3.8/site-packages/galerkin_transformer/model.py", line 2, in <module>
    from libs.layers import *
ModuleNotFoundError: No module named 'libs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_galerkin_transformer.py", line 7, in <module>
    from galerkin_transformer.model import *
  File "xxx/lib/python3.8/site-packages/galerkin_transformer/model.py", line 5, in <module>
    from layers import *
ModuleNotFoundError: No module named 'layers'
```
* 应该是包的路径管理有些问题，麻烦您debug一下（或者是我哪个地方搞错了？）

**Comment by scaomath** [comment]
Thanks! Let me fix it tomorrow.

**Comment by scaomath** [comment]
Sorry for the delay.
Please try
```bash
pip install galerkin-transformer==0.2.1
```
and then:
```python
 from galerkin_transformer.model import *
```
